### ISSUE TITLE
Suggestion & small bug

### ISSUE THREAD

**Issue by Son-of-Cronus** [tomdoyle87/osmc-linux-installer#2]
Ubuntu  when installed from deb.:
The app in the menu defaults to:  applications>Sound & Video
Accessories, like the Pi-Imager or Etcher seems a more logical choice to me.

bug:
I cant seem to resize the GUI. (seems a bit big, the buttons seem to render to big) 

I hope you can push this one day to OSMC officially as an update. It was by chance i found it!

**Comment by samnazarko** [comment]
I will push it before the end of the month officially to the OSMC site

Tom has done a great job

On 20 May 2022, at 22:53, Hades ***@***.***> wrote:

﻿

Ubuntu when installed from deb.:
The app in the menu defaults to: applications>Sound & Video
Accessories, like the Pi-Imager or Etcher seems a more logical choice to me.

bug:
I cant seem to resize the GUI. (seems a bit big, the buttons seem to render to big)

I hope you can push this one day to OSMC officially as an update. It was by chance i found it!

**Comment by Son-of-Cronus** [comment]
Yes, he did! 

Not everybody on Linux is proficient in the terminal! And/or has acces to a winblows PC..
Will install another Pi 4, and report back any issue/bug if i encounter one that is.

Only small thingy i found so far was the copyright still needs to be updated (2015)

**Comment by tomdoyle87** [comment]
Hi, 

"The app in the menu defaults to: applications>Sound & Video
Accessories, like the Pi-Imager or Etcher seems a more logical choice to me."

This is where the original Linux installer placed it in the menu. @samnazarko do you think this should change as suggested?

"I cant seem to resize the GUI. (seems a bit big, the buttons seem to render to big)"

@Son-of-Cronus what resolution is your display? There is a bit of a flaky  work around for HiDPI and 4k.

"Only small thingy i found so far was the copyright still needs to be updated (2015)"

This matches the installers for Windows & Mac, will wait for upstream change. 

Regards Tom.

**Comment by Son-of-Cronus** [comment]
Hi @tomdoyle87 ,

I just changed the menu link myself to Accessories. No problem.

My screens resolution is 2560x1440...
That might explain the bit oversized buttons.
The copyright notice i just brought up cause it is an easy thing to forget/skip.
(speaking out of experience..)

**Comment by tomdoyle87** [comment]
"My screens resolution is 2560x1440...
That might explain the bit oversized buttons."

Any chance of a screenshot?

**Comment by Son-of-Cronus** [comment]
Sure! If opened in seperate tab it's very clear to see.
![image](https://user-images.githubusercontent.com/79419919/169663676-0dc1a07d-4266-4cab-8862-56302480c196.png)

**Comment by tomdoyle87** [comment]
Not sure I can do anything about the buttons.  But It would look better if use a local build... was in the centre. I think this is a rendering issue. I haven't current got access to a display over 1080p, so may take a while for me to look at this.

**Comment by Son-of-Cronus** [comment]
Nitpicking now, but...
![image](https://user-images.githubusercontent.com/79419919/169664778-ffbfed77-3f46-4b88-960d-e8c0f1c94e8b.png)

**Comment by Son-of-Cronus** [comment]
All other screens seem perfect to me.

**Comment by tomdoyle87** [comment]
thanks for these, when I get on a bigger display. I'll take a look at fixing these 2 sections.

**Comment by Son-of-Cronus** [comment]
;) you're welcome, here to help

**Comment by tomdoyle87** [comment]
Hi @Son-of-Cronus,

Could you please try this test release:

https://nc.tomsdomain.co.uk/index.php/s/sydebaiEYegci5x

This hopefully fix the alignment issues on the screens you provided, for screens greater than 1080p. Please be advised this will not display correctly on screens that are 1080p or less (can fix that later). 

Menu still defaults to applications>Sound & Video

Regards Tom.

**Comment by tomdoyle87** [comment]
Hi @Son-of-Cronus,

The latest release: 

https://github.com/tomdoyle87/osmc-linux-installer/releases/latest

Should fix the alignment issues for resolutions higher than 1080p. Please may you test and confirm?

Thanks Tom.

**Comment by tomdoyle87** [comment]
Closing as I believe is resolved with the latest issue.

**Comment by tomdoyle87** [comment]
Fixed in v128.7
